# Generated by Django 4.1.4 on 2022-12-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyPay', '0002_account_first_name_account_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='payment_type',
            field=models.CharField(choices=[('CC', 'CC'), ('CASH', 'Cash'), ('UPI', 'UPI')], default='Online', max_length=16),
        ),
    ]
