# Generated by Django 4.1.4 on 2022-12-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyPay', '0005_alter_transactions_receiver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='amt_credit',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='amt_debit',
        ),
        migrations.AddField(
            model_name='balance',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
