# Generated by Django 4.1.4 on 2022-12-22 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyPay', '0007_transactions_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='account',
        ),
    ]
