# Generated by Django 3.2.9 on 2023-01-24 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyPay', '0010_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
