# Generated by Django 3.2.9 on 2023-02-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyPay', '0013_auto_20230205_1629'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
